spring.datasource.url=jdbc:h2:file:./data/restaurant_demo;MODE=MySQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
app.payments-mode=demo
